name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.20.2]  # usa la misma versión 

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependencias
      run: npm install

    - name: Compilar Angular
      run: npm run build --if-present

    #- name: Ejecutar pruebas
     # run: npm test -- --watch=false --browsers=ChromeHeadless